apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: standard  # Changed to existing StorageClass in your cluster
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/lib/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-tweetdb
spec:
  storageClassName: standard  # Changed to existing StorageClass in your cluster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim-userdb
spec:
  storageClassName: standard  # Changed to existing StorageClass in your cluster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

