apiVersion: v1
kind: Service
metadata:
  name: tweetdb-mysql-service
spec:
  ports:
  - port: 3306
  selector:
    app: tweetdb-mysql
  clusterIP: None

---
apiVersion: v1
kind: Service
metadata:
  name: userdb-mysql-service
spec:
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    app: userdb-mysql
  clusterIP: None

