apiVersion: v1
kind: Service
metadata:
  labels:
    app: tweets-service
  name: tweets-service
  namespace: default
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8001
  selector:
    app: tweets-service

