apiVersion: v1
kind: Service
spec:
  name: rabbitmq
  ports:
  - port: 15672
    targetPort: 15672
    name: web
  - port: 5672
    targetPort: 5672
    name: amqp
  selector:
    app: rabbitmq
  type: LoadBalancer
  ports:
  - port: 15672
  selector:
    app: web-app

